_BASE_: "../Base-RCNN-FPN.yaml" 
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 2
SOLVER:
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.01
  STEPS: (1000,)
  MAX_ITER: 1000
  AMP:
    ENABLED: True
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: False
  TRAIN_LABEL: ("train_labeled",)
  TRAIN_UNLABEL: ("train_unlabeled",)
  TEST: ("val",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BURN_UP_STEP: 1000
  ANALYSIS_PRINT_FRE: 100
TEST:
  EVAL_PERIOD: 100
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT:
  MIN_SIZE_TRAIN: (2000,)
  MAX_SIZE_TRAIN: 2560
  MIN_SIZE_TRAIN_SAMPLING: "choice"
## To change
DATA_DIR: /mnt/voyage/ubteacher_io/training_data/
FMT: .svs, .tif
TRAIN_FRACTION: 0.8
CLASS_CONVERTER: None