_BASE_: "../Faster-RCNN/Base-RCNN-FPN.yaml" 
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 6
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: true
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.01
  STEPS: (500,)
  MAX_ITER: 500
  AMP:
    ENABLED: False
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("train",)
  TEST: ("val",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  PSEUDO_BBOX_SAMPLE: "thresholding"
  PSEUDO_BBOX_SAMPLE_REG: "thresholding" # 0.5 when PSEUDO_BBOX_SAMPLE_REG = 'thresholding'
  BBOX_THRESHOLD: 0.5
  BBOX_THRESHOLD_REG: 0.5 # 0.5 when PSEUDO_BBOX_SAMPLE_REG = 'thresholding'
  BBOX_CTR_THRESHOLD: 0.0
  BBOX_CTR_THRESHOLD_REG: 0.0
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 250
  EMA_KEEP_RATE: 0.9999
  UNSUP_LOSS_WEIGHT: 3.0
  UNSUP_REG_LOSS_WEIGHT: 0.2
  CONSIST_CTR_LOSS: "pseudo"
  PSEUDO_CLS_IGNORE_NEAR: False
  PSEUDO_CTR_THRES: 0.5
  SOFT_CLS_LABEL: False
  CLS_LOSS_METHOD: "focal"
  CLS_LOSS_PSEUDO_METHOD: "focal"
  TS_BETTER: 0.1
  CONSIST_REG_LOSS: "ts_locvar_better_nms_nll_l1"
  ANALYSIS_PRINT_FRE: 5000
  ANALYSIS_ACCUMLATE_FRE: 50
TEST:
  EVAL_PERIOD: 100
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT:
  MIN_SIZE_TRAIN: (1333,)
  MAX_SIZE_TRAIN: 1440
  MIN_SIZE_TRAIN_SAMPLING: "choice"
## New stuff
NUMPY: True
#UNLABELED_DIR: /mnt/RSX/Datasets_pathology/GT_2023/TissueFinderV2/unlabeled
DATASET_DICTS: /home/chao_lab/SynologyDrive/chaolab_AI_path/unbiased_teacher2/dataseed/tfv2_2.json
REGISTER: True
ANNO_DIR: /mnt/RSX/Datasets_pathology/
IMG_DIR: /mnt/RSX/Datasets_pathology/GT_2023/TissueFinderV2/
FMT: .svs, .tif
TRAIN_FRACTION: 0.8
SET_SEED: False
BOX_ONLY: True
DATASEED: /home/chao_lab/SynologyDrive/chaolab_AI_path/unbiased_teacher2/dataseed/tfv2_2.json
DEBUG: False
CAT_MAP: {"1" : "test"}
CLASS_CONVERTER: None