PARENTDIR: '/home/chao_lab/GT_2023/LesionFinder'
_BASE_: "../FCOS/Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS: # Defaults for now
    CENTER_SAMPLE: False
    NMS_CRITERIA_TRAIN: "cls" # use cls-only to select pseudo-labels
    NMS_CRITERIA_TEST: "cls_n_ctr" # use cls + centerness score to select pseudo-labels
    NMS_CRITERIA_REG_TRAIN: "cls_n_loc" # use cls + localization uncertainty to select pseudo-labels
    POS_RADIUS: 1.5
    YIELD_PROPOSAL: True
    UNIFY_CTRCLS: False
    DFL_WEIGHT: 0.0
    REG_DISCRETE: True
    KL_LOSS: True
    KLLOSS_WEIGHT: 0.05
    KL_LOSS_TYPE: "nlloss"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (200000,)
  MAX_ITER: 200000
  IMG_PER_BATCH_LABEL: 5
  IMG_PER_BATCH_UNLABEL: 5
  BASE_LR: 0.01 #Changed from 0.005 in v2.7
  AMP:
    ENABLED: True
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
  FILTER_EMPTY_ANNOTATIONS: false # if this is true, you will lose images without annotations
  NUM_WORKERS: 8
DATASETS: 
  CROSS_DATASET: true
  TRAIN_LABEL: ("ROI_train_labeled",)
  TRAIN_UNLABEL: ("ROI_train_unlabeled",)
  TEST: ("ROI_val",)
SEMISUPNET:
  Trainer: "ubteacher"
  PSEUDO_BBOX_SAMPLE: "thresholding"
  PSEUDO_BBOX_SAMPLE_REG: "thresholding" # 0.5 when PSEUDO_BBOX_SAMPLE_REG = 'thresholding'
  BBOX_THRESHOLD: 0.5 #Changed from 0.7 in v2.6
  BBOX_THRESHOLD_REG: 0.5 # 0.5 when PSEUDO_BBOX_SAMPLE_REG = 'thresholding'
  BBOX_CTR_THRESHOLD: 0.0
  BBOX_CTR_THRESHOLD_REG: 0.0
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 10000
  EMA_KEEP_RATE: 0.9999
  UNSUP_LOSS_WEIGHT: 3.0
  UNSUP_REG_LOSS_WEIGHT: 0.2
  CONSIST_CTR_LOSS: "pseudo"
  PSEUDO_CLS_IGNORE_NEAR: False
  PSEUDO_CTR_THRES: 0.5
  SOFT_CLS_LABEL: False
  CLS_LOSS_METHOD: "focal"
  CLS_LOSS_PSEUDO_METHOD: "focal"
  TS_BETTER: 0.1
  CONSIST_REG_LOSS: "ts_locvar_better_nms_nll_l1"
  ANALYSIS_PRINT_FRE: 5000
  ANALYSIS_ACCUMLATE_FRE: 50
TEST:
  EVAL_PERIOD: 5000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (800,1333)
  MAX_SIZE_TRAIN: 2000
  MAX_SIZE_TEST: 2560
  MIN_SIZE_TRAIN_SAMPLING: "range"
#Put train_val_split.json formatted json here
DATASEED: '/home/chao_lab/SynologyDrive/chaolab_AI_path/unbiased_teacher2/dataseed/OSCC_TCGA_FullMix_1008.json'


