PARENTDIR: '/home/chao_lab/GT_2023/LesionFinder'
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101 #Changed from 50 in v2.6
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: true
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (200000,)
  MAX_ITER: 200000
  IMG_PER_BATCH_LABEL: 5
  IMG_PER_BATCH_UNLABEL: 5
  BASE_LR: 0.01 #Changed from 0.005 in v2.7
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
  FILTER_EMPTY_ANNOTATIONS: false # if this is true, you will lose images without annotations
  NUM_WORKERS: 8
DATASETS: 
  CROSS_DATASET: true
  TRAIN_LABEL: ("ROI_train_labeled",)
  TRAIN_UNLABEL: ("ROI_train_unlabeled",)
  TEST: ("ROI_val",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.5 #Changed from 0.7 in v2.6
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0 #Changed from 3.0 in v2.6
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
  EVAL_PERIOD: 5000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (400, 1200)
  MAX_SIZE_TRAIN: 2000
  MAX_SIZE_TEST: 2560
  MIN_SIZE_TRAIN_SAMPLING: "range"
#Put train_val_split.json formatted json here
DATASEED: '/home/chao_lab/SynologyDrive/chaolab_AI_path/unbiased_teacher2/dataseed/OSCC_TCGA_FullMix_1008.json'


