_BASE_: "../Base-RCNN-FPN.yaml"
DATALOADER:
  NUM_WORKERS: 8
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES:
    - - 16
    - - 32
    - - 64
    - - 128
    - - 256
  FCOS:
    NUM_CLASSES: 5
  RETINANET:
    NUM_CLASSES: 5
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
    NUM_CLASSES: 5
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: true
  SEM_SEG_HEAD:
    NUM_CLASSES: 5 
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (50000,)
  MAX_ITER: 50000
  IMG_PER_BATCH_LABEL: 5
  IMG_PER_BATCH_UNLABEL: 5
  BASE_LR: 0.005
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
DATASETS:
  CROSS_DATASET: true
  TEST: ("ROI_val",)
  TRAIN: ("ROI_train",)
  TRAIN_LABEL: ("ROI_train_labeled",)
  TRAIN_UNLABEL: ("ROI_train_unlabeled",)
  #NUM_CLASSES: 5
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
  EVAL_PERIOD: 2000
  AUG:
    MAX_SIZE: 2560
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  CROP:
    ENABLED: false 
  MIN_SIZE_TRAIN: (800, 1200)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 2560
  MAX_SIZE_TEST: 2560
  

