PARENTDIR: '/home/chao_lab/GT_2023/LesionFinder/COCOPath'
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  NUM_CLASSES: 4
  RESNETS:
    DEPTH: 101 #Changed from 50 in v2.6
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: true
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (200000,)
  MAX_ITER: 200000 
  IMS_PER_BATCH: 12
  IMG_PER_BATCH_LABEL: 12
  IMG_PER_BATCH_UNLABEL: 0
  BASE_LR: 0.005
DATALOADER:
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
  FILTER_EMPTY_ANNOTATIONS: False
DATASETS: 
  CROSS_DATASET: False
  TRAIN: ("ROI_train",)
  TRAIN_LABEL: ("ROI_train",)
  #TRAIN_UNLABEL: ("ROI_train_unlabeled",)
  TEST: ("ROI_val",)
SEMISUPNET:
  Trainer: "baseline" #Testing new trainer
  BBOX_THRESHOLD: 0.7 
TEST:
  EVAL_PERIOD: 5000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT: # scale jittering (follow soft teacher)
  MIN_SIZE_TRAIN: (800, 2560)
  MIN_SIZE_TRAIN_SAMPLING: "range"
#Put train_val_split.json formatted json here -- deprecated because of masks
#DATASEED: '/home/chao_lab/SynologyDrive/ROI_detection2/outputs/ROIdet-multi_20230906/train-val-split.json'
