_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "/home/chao_lab/SynologyDrive/ROI_detection2/outputs/ROIdet-multi_20230709/model_final.pth"
  MASK_ON: False
  BACKBONE:
    NAME: build_resnet_backbone
  RESNETS:
    NUM_GROUPS: 16
    STRIDE_IN_1X1: False
    DEPTH: 101
    WIDTH_PER_GROUP: 4
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss_BoundaryVar"
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "nlloss"
    CLS_AGNOSTIC_BBOX_REG: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (5000,)
  MAX_ITER: 10000
  IMG_PER_BATCH_LABEL: 5
  IMG_PER_BATCH_UNLABEL: 5
  BASE_LR: 0.005

DATALOADER:
  NUM_WORKERS: 8
  SUP_PERCENT: 100.0
  RANDOM_DATA_SEED: 0
DATASETS:
  CROSS_DATASET: True
  TRAIN: ("ROI_train",)
  TRAIN_LABEL: ("ROI_train_labeled",)
  TRAIN_UNLABEL: ("ROI_train_unlabeled",)
  TEST: ("ROI_val",)
SEMISUPNET:
  Trainer: "ubteacher_rcnn"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 3.0
  UNSUP_REG_LOSS_WEIGHT: 1.0
TEST:
  EVAL_PERIOD: 5000
  EVALUATOR: "COCOeval"
  VAL_LOSS: False
INPUT:
  MIN_SIZE_TRAIN:
  - 960
  - 1280
  MAX_SIZE_TRAIN: 1666
